package com.example.dbtest.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.dbtest.greendao.dao.users;

import com.example.dbtest.greendao.dao.usersDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig usersDaoConfig;

    private final usersDao usersDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        usersDaoConfig = daoConfigMap.get(usersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        usersDao = new usersDao(usersDaoConfig, this);

        registerDao(users.class, usersDao);
    }
    
    public void clear() {
        usersDaoConfig.getIdentityScope().clear();
    }

    public usersDao getUsersDao() {
        return usersDao;
    }

}
